package edu.kit.varijoern.analyzers;

import edu.kit.varijoern.composers.FeatureMapper;
import org.prop4j.Node;

import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * Contains information about a finding and the variants in which it was found. Findings are aggregated into one finding
 * and stored in an instance of this class if their evidence refers to the same source code locations.
 */
public class FindingAggregation {
    private final Finding finding;
    private final Set<Map<String, Boolean>> affectedAnalyzedVariants;
    private final List<FeatureMapper> relatedFeatureMappers;

    /**
     * Creates a new {@link FindingAggregation} containing the specified information.
     *
     * @param finding                  the finding
     * @param affectedAnalyzedVariants the variants in which the finding was found
     * @param relatedFeatureMappers    the feature mappers that were generated by the composer for each of the affected
     *                                 analyzed variants
     */
    public FindingAggregation(Finding finding, Set<Map<String, Boolean>> affectedAnalyzedVariants,
                              List<FeatureMapper> relatedFeatureMappers) {
        this.finding = finding;
        this.affectedAnalyzedVariants = affectedAnalyzedVariants;
        this.relatedFeatureMappers = relatedFeatureMappers;
    }

    /**
     * Returns the finding.
     *
     * @return the finding
     */
    public Finding getFinding() {
        return finding;
    }

    /**
     * Returns the variants in which the finding was found.
     *
     * @return the affected analyzed variants
     */
    public Set<Map<String, Boolean>> getAffectedAnalyzedVariants() {
        return affectedAnalyzedVariants;
    }

    /**
     * Returns the presence conditions determined using the feature mappers for the affected analyzed variants. If a
     * condition could not be determined using a feature mapper, it is not included in the result.
     *
     * @return the presence conditions
     */
    public Set<Node> getPossibleConditions() {
        return relatedFeatureMappers.stream()
                .map(finding::getCondition)
                .flatMap(Optional::stream)
                .collect(Collectors.toSet());
    }

    @Override
    public String toString() {
        return "Finding: %s%nAnalyzed affected variants: %s%nPossible conditions: %s"
                .formatted(finding, affectedAnalyzedVariants, getPossibleConditions());
    }
}
