package edu.kit.varijoern.composers.kbuild;

import edu.kit.varijoern.composers.PresenceConditionMapper;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.prop4j.And;
import org.prop4j.Node;

import java.nio.file.Path;
import java.util.Map;
import java.util.Optional;

/**
 * Determines the presence conditions of individual code lines in a file generated by {@link KbuildComposer}.
 */
public class KbuildPresenceConditionMapper implements PresenceConditionMapper {
    private final Map<Path, Node> filePresenceConditions;
    private final Map<Path, LinePresenceConditionMapper> linePresenceConditionMappers;
    private final Map<Path, GenerationInformation> generationInformation;
    private static final Logger logger = LogManager.getLogger();

    /**
     * Creates a new {@link KbuildPresenceConditionMapper} with the specified information.
     *
     * @param filePresenceConditions the presence conditions of the individual files. This list need not be complete.
     *                               The keys are the paths to the (compiled) object files, relative to the source
     *                               directory.
     * @param linePresenceConditionMappers     the {@link LinePresenceConditionMapper}s for the individual files. This list should contain
     *                               an entry for all files for which the composer detected a GCC call. The keys are
     *                               the paths to the files generated by the composer, relative to the output directory.
     * @param generationInformation  a map from paths of generated files to information about the generation process.
     *                               The keys are the paths to the files generated by the composer, relative to the
     *                               output directory.
     */
    public KbuildPresenceConditionMapper(Map<Path, Node> filePresenceConditions,
                                         Map<Path, LinePresenceConditionMapper> linePresenceConditionMappers,
                                         Map<Path, GenerationInformation> generationInformation) {
        this.filePresenceConditions = filePresenceConditions;
        this.linePresenceConditionMappers = linePresenceConditionMappers;
        this.generationInformation = generationInformation;
    }

    @Override
    public Optional<Node> getPresenceCondition(Path file, int lineNumber) {
        GenerationInformation fileGenerationInformation = this.generationInformation.get(file.normalize());
        if (fileGenerationInformation == null) {
            logger.warn("Could not find generation information for file {}", file.normalize());
            return Optional.empty();
        }
        Path originalPath = fileGenerationInformation.originalPath();
        Path originalPathToObjectFile = originalPath.getParent().resolve(
                originalPath.getFileName().toString().replaceAll("\\.[a-zA-Z0-9]+$", ".o")
        );
        Node filePresenceCondition = this.filePresenceConditions.get(originalPathToObjectFile.normalize());
        if (filePresenceCondition == null)
            return Optional.empty();
        LinePresenceConditionMapper linePresenceConditionMapper = this.linePresenceConditionMappers.get(file.normalize());
        if (linePresenceConditionMapper == null)
            return Optional.empty();

        return linePresenceConditionMapper.getPresenceCondition(lineNumber)
                .map(linePresenceCondition -> new And(filePresenceCondition, linePresenceCondition));
    }
}
